#!/bin/bash
# fix-security-urgent.sh - Correções de segurança urgentes pós-auditoria

set -e

echo "🔒 Aplicando correções de segurança urgentes..."
echo ""

# 1. Gerar EVOLUTION_WEBHOOK_SECRET se não existe
if ! grep -q "EVOLUTION_WEBHOOK_SECRET" .env.local; then
  echo "📝 Gerando EVOLUTION_WEBHOOK_SECRET..."
  SECRET=$(openssl rand -hex 32)
  echo "" >> .env.local
  echo "# Generated by fix-security-urgent.sh on $(date)" >> .env.local
  echo "EVOLUTION_WEBHOOK_SECRET=\"$SECRET\"" >> .env.local
  echo "✅ EVOLUTION_WEBHOOK_SECRET adicionado"
else
  echo "⚠️  EVOLUTION_WEBHOOK_SECRET já existe, pulando"
fi

# 2. Adicionar env vars faltando em .env.local
echo ""
echo "📝 Verificando env vars críticas..."

add_if_missing() {
  VAR_NAME=$1
  VAR_VALUE=$2
  
  if ! grep -q "^${VAR_NAME}=" .env.local; then
    echo "${VAR_NAME}=\"${VAR_VALUE}\"" >> .env.local
    echo "✅ Adicionado: $VAR_NAME"
  else
    echo "⚠️  Já existe: $VAR_NAME"
  fi
}

# Adicionar vars faltando (copiar do .env.production se disponível)
if [ -f .env.production ]; then
  echo "📋 Copiando configurações de .env.production..."
  
  # DATABASE_URL (alias para SUPABASE_DB_URL)
  if ! grep -q "^DATABASE_URL=" .env.local && grep -q "^SUPABASE_DB_URL=" .env.local; then
    DB_URL=$(grep "^SUPABASE_DB_URL=" .env.local | cut -d= -f2-)
    add_if_missing "DATABASE_URL" "$DB_URL"
  fi
  
  # JWT_SECRET
  if ! grep -q "^JWT_SECRET=" .env.local; then
    JWT=$(grep "^JWT_SECRET=" .env.production | cut -d= -f2- || echo "pratica_jwt_$(openssl rand -hex 16)")
    add_if_missing "JWT_SECRET" "$JWT"
  fi
  
  # NEXTAUTH_SECRET
  if ! grep -q "^NEXTAUTH_SECRET=" .env.local; then
    NEXTAUTH=$(grep "^NEXTAUTH_SECRET=" .env.production | cut -d= -f2- || echo "pratica_nextauth_$(openssl rand -hex 16)")
    add_if_missing "NEXTAUTH_SECRET" "$NEXTAUTH"
  fi
  
  # NODE_ENV
  add_if_missing "NODE_ENV" "production"
  
  # PORT
  add_if_missing "PORT" "3000"
  
  # WEBHOOK_BASE_URL (detectar IP automaticamente)
  if ! grep -q "^WEBHOOK_BASE_URL=" .env.local; then
    IP=$(hostname -I | awk '{print $1}' || echo "localhost")
    add_if_missing "WEBHOOK_BASE_URL" "http://${IP}:3000"
  fi
fi

echo ""
echo "✅ Correções aplicadas!"
echo ""
echo "⚠️  PRÓXIMOS PASSOS:"
echo "1. Revisar .env.local e verificar valores"
echo "2. Rebuild: npm run build"
echo "3. Restart: pm2 restart pratica"
echo "4. Monitorar logs: pm2 logs pratica --lines 50"
echo ""
echo "🔐 IMPORTANTE: Guarde as secrets geradas em local seguro (1Password, Vault, etc)"
